
; Queries as generated by functions in report

(time (query:X->Known
            #f
            (set->list
            (get-non-deprecated-mixed-ins-and-descendent-predicates*-in-db
            '("biolink:regulates")))
            (set->list
            (get-descendent-curies*-in-db
            (curies->synonyms-in-db (list "HGNC:3236"))))))


(time (query:Known->X
            (set->list
            (get-descendent-curies*-in-db
            (curies->synonyms-in-db (list "PUBCHEM.COMPOUND:441207"))))
            (set->list
            (get-non-deprecated-mixed-ins-and-descendent-predicates*-in-db
            '("biolink:regulates")))
            #f))

; Queries as generated by 

(time (query:Known->X-scored
            (set->list
            (get-descendent-curies*-in-db
            (curies->synonyms-in-db (list "PUBCHEM.COMPOUND:5291"))))
            (set->list
            (get-non-deprecated-mixed-ins-and-descendent-predicates*-in-db
            '("biolink:regulates")))
            #f
            TOP_BUCKET_NUMBERS))




